### PR TITLE
Reformatting generation scripts

### PR DESCRIPTION
**Pull request by vigji**
Here's my take at writing some utility functions to keep atlases consistent.

I have updated only the `test_atlas.py` script, so have a look at that for the current state of atlas generation! I hope that the flow is fully descripted there.

Random notes:
- The generation of the readable files we were discussing is still not addressed, I am happy if you want to take care of that!
- I thought that it might also be good to enforce consistency on the reference and annotations stacks. What do you think?
- Some controls might be a bit tight and could be tested/handled better. But deciding those things require some crash tests so let me know what you think trying them out
- I cleaned out the allenSDK dependency, @FedeClaudi feel free to improve structure classes for your taste :)
- tests are still not updated;
- I did some try at automatic docs conversion using `pyment` and I was positively impressed. Moving the doc style of entire packages should require only some fixing here and there, so I would definitively keep numpydoc style for the project

### CODE REVIEW

**Comment by FedeClaudi** [comment]
Looks good, it will have to be integrated with
https://github.com/brainglobe/brainatlas-api/pull/14#issue-424350577

and 

https://github.com/brainglobe/atlas-scripts/pull/1#issue-424342060

but it should be fairly easy

**Comment by adamltyson** [comment]
To be clear, are we scrapping `atlas-scripts`, and keeping everything together in this repo? In which case, can we have tools like `allensdk` as optional dependencies (we could just stick them into the `[dev]` group.

I removed the `allensdk` dependency in #14, so I propose that:
* @vigji you approve and merge #14 
* We then add `allensdk` to the `[dev]` dependencies and then merge this PR to master.

**Comment by adamltyson** [comment]
Dammit Fede beat me to it

**Comment by adamltyson** [comment]
Once these are merged (and if you guys ever stop working), I'll start to work on:
* Automatic generation of [this other mouse atlas](https://www.nature.com/articles/s41467-019-13057-w)
* JSON -> CSV and CSV -> JSON conversion

**Comment by vigji** [comment]
> To be clear, are we scrapping `atlas-scripts`, and keeping everything together in this repo? In which case, can we have tools like `allensdk` as optional dependencies (we could just stick them into the `[dev]` group.

Yep, makes perfect sense!

Well, sorry for the overlaps, I hope that as things grow the niches get more separated :D

**Comment by FedeClaudi** [comment]
> Automatic generation of this other mouse atlas

Yes please!

> Well, sorry for the overlaps, I hope that as things grow the niches get more separated :D

No worries, it's bound to happen as we are all working on this at the same time.

**Comment by FedeClaudi** [comment]
Let's archive https://github.com/brainglobe/atlas-scripts once we have finished merging everything?

**Comment by adamltyson** [comment]
> Let's archive https://github.com/brainglobe/atlas-scripts once we have finished merging everything?

agree

**Comment by vigji** [comment]
> > Let's archive https://github.com/brainglobe/atlas-scripts once we have finished merging everything?

agree!

Agree

**Comment by FedeClaudi** [comment]
are the latest changes to atlas-scripts integrted here or do you need me to move stuff over?

**Comment by vigji** [comment]
No, I think you would need to move stuff over, there's only the allen and the zebrafish scripts right now

**Comment by vigji** [comment]
On a different note, I added the config file for configuring the pre-commits hooks according to [these instructions](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/l). 
To install them it should be enough to do `pre-commit install` in the project dir. There's black formatting and flake8, with a previsionary but expandable list of exceptions.

**Comment by adamltyson** [comment]
> On a different note, I added the config file for configuring the pre-commits hooks according to these instructions.

This looks to work well. We should add flake8 tests to the test script too.

**Pull request merged**
