### PR TITLE
Unified ARA & Franklin-Paxinos atlas

### PR DESCRIPTION
**Pull request by adamltyson**
Still need to generate the non-terminal mesh files.

### CODE REVIEW

**Comment by adamltyson** [comment]
There's a lot of code copied from the existing atlas generation scripts, so this should probably be extracted into functions.

Another thing I noticed, we're not consistent with the mesh names. The ARA and zfish meshes are `id.obj`, but the others are `abbreviation.obj`. I assume that the ID is default for the ARA, but the abbreviation is possibly more useful as we can load them directly rather than by parsing the JSON.

**Comment by vigji** [comment]
My concern with the abbreviations are:
 1. current fish does not provide abbreviations (no big deal, it's just the full name though)
 2. full flexibility on strings for names/annotations might generate invalid filenames maybe?

No other concerns though, if we are sure 2 is not an issue I am happy to move to name,

**Comment by FedeClaudi** [comment]
For the rat and human atlas I've been using `id+'.obj'` to keep consistency with the FishAtlas, but I don't mind either way.

**Comment by adamltyson** [comment]
I copied this from the rat atlas script which deals with (2) fairly well:
```python
    savepath = str(
        meshes_dir_path
        / f'{structure["id"]}.obj'.replace("/", "-").replace("\\", "-")
    )
```

**Comment by FedeClaudi** [comment]
I will write some (probably vtkplotter based) code to extract meshes + possibily beautify them so that stuff will be exported to functions.

**Comment by adamltyson** [comment]
Just realised I've been an idiot. None of the atlases have the abbreviation (only mine), so I can move to the ID easily.

**Comment by FedeClaudi** [comment]
Hehe. Do you want me to revert the PR so that you can update the code?

**Comment by vigji** [comment]
> There's a lot of code copied from the existing atlas generation scripts, so this should probably be extracted into functions.

Agreed. We can have a single function that takes metadata parameters, a numpy reference stack, a numpy annotation stac, a list of meshes (or meshes files not having to load them?) and does the entire saving part.

**Comment by vigji** [comment]
loosely related - do you guys think that we can assume ids to be always positive?

**Comment by adamltyson** [comment]
> Hehe. Do you want me to revert the PR so that you can update the code?

Yes please, I'm still adding stuff. Sorry I should have marked it as draft.

**Pull request merged**
