### PR TITLE
Brought togehter the latest changes in script generation

### PR DESCRIPTION
**Pull request by FedeClaudi**
merged the latest changes to atlas scripts and brainatlas-api

I've moved `atlas_gen` out of `brainatlas_api` though as there's no need to have these one-off scripts as part of the pip-isntallable package. 

If that's a problem we can move it back in.

### CODE REVIEW

**Comment by FedeClaudi** [comment]
Things left to do:

- Using @vigji 's latest code to make sure that `ratatlas.py` conforms to the structure and standards of the other atlas generating scrips.  (@FedeClaudi )
- Making sure that `mouseatlas.py` and `fishatlas.py` use the `metadata_utils.py` functions to create the .txt and .csv files (@vigji )
- Adding the cration of `structures.csv` to `metadata_utils.py` (@adamltyson )

**Comment by adamltyson** [comment]
> I've moved atlas_gen out of brainatlas_api though as there's no need to have these one-off scripts as part of the pip-isntallable package.

I'm not sure, but I think the current form will:
* Install two packages (`atlas_gen` and `brainatlas_api`)
* Break the tests

I've fixed the tests in master, could you merge master, and see if they can be fixed?

**Comment by FedeClaudi** [comment]
Ops, my ignorance of how this stuff works shows. 

I will close this, merge from master and move atlas_gen back into brainatlas_api, then submit again

**Comment by adamltyson** [comment]
> no need to have these one-off scripts as part of the pip-isntallable package.

I think we can do this by adding the directories to be ignored for installation to here:
https://github.com/brainglobe/brainatlas-api/blob/1945eb4294c12d112f3b77cd62e7b06b0bad1519/setup.py#L27

**Pull request closed without merging**
